CREATE TABLE IF NOT EXISTS `editorials` (
  `editid` BIGINT NOT NULL AUTO_INCREMENT,
  `editnom` VARCHAR(45) NULL DEFAULT NULL,
  `editnum` VARCHAR(8) NULL DEFAULT NULL,
  `editdirec` VARCHAR(250) NULL DEFAULT NULL,
  `editest` CHAR(3) NULL DEFAULT 'ACT',
  PRIMARY KEY (`editid`))